### PR TITLE
0.65. failing

### PR DESCRIPTION
**Pull request by critesjosh**
currenlty failing `yarn test` with the following error:

```
txe-1          | Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'jest-mock-extended' imported from /usr/src/yarn-project/simulator/dest/public/fixtures/index.js
txe-1          |     at new NodeError (node:internal/errors:405:5)
txe-1          |     at packageResolve (node:internal/modules/esm/resolve:916:9)
txe-1          |     at moduleResolve (node:internal/modules/esm/resolve:973:20)
txe-1          |     at defaultResolve (node:internal/modules/esm/resolve:1193:11)
txe-1          |     at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:403:12)
txe-1          |     at ModuleLoader.resolve (node:internal/modules/esm/loader:372:25)
txe-1          |     at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:249:38)
txe-1          |     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:39)
txe-1          |     at link (node:internal/modules/esm/module_job:75:36) {
txe-1          |   code: 'ERR_MODULE_NOT_FOUND'
txe-1          | }
txe-1          | 
txe-1          | Node.js v18.19.1
txe-1 exited with code 1
```

### CODE REVIEW

**Comment by wei3erHase** [comment]
if it serves any help: i also had that issue while trying to run the sandbox in 0.64.0, and it specifically fails on `aztec test`, not on the JS part of the test, running `NODE_NO_WARNINGS=1 node --experimental-vm-modules $(yarn bin jest) --no-cache --runInBand --config jest.integration.config.json` works ok

**Comment by critesjosh** [comment]
The next release should have a fix for this. I am trying to get it out today

**Review by wei3erHase — APPROVED** [review]
working 👌

**Comment by critesjosh** [comment]
ah thanks, already updated here https://github.com/AztecProtocol/aztec-starter/commit/64fb0cdf409d136ea548684634aba9e0f654f1f8

**Pull request closed without merging**
